name: build

on:
  schedule:
    - cron: '0 3 * * 5'
  push:
    branches:
      - main
  workflow_dispach:
   
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: installResources.sh

    - name: Build exe
      run: pyinstaller --onefile konwerter.py

    - name: Upload exe
      uses: actions/upload-artifact@v3
      with:
        name: konwerter
        path: dist/konwerter.exe

